[package]
name = "one_brc"
version = "0.1.0"
edition = "2021"

[profile.release]
debug=true
lto=true
codegen-units=1
opt-level=3

[dependencies]
crossbeam = "0.8.4"
fxhash = "0.2.1"
memmap2 = "0.9.5"
tikv-jemallocator = "0.6.0"

